### ISSUE TITLE
[FEATURE] Refresh button for refreshing a single server.

### ISSUE THREAD

**Issue by UsainSrht** [Thatsmusic99/NoRefreshScroll#2]
![image](https://github.com/Thatsmusic99/NoRefreshScroll/assets/59025999/02c3f257-cb49-4701-8855-7ef7fd11bf27)
You know when you hit refresh button, it takes some time to ping all the servers. It might be nice addition to be able to ping a single server. I'm thinking of a button that shows when you hover the server.

**Comment by Thatsmusic99** [comment]
TBH this is not something for NoRefreshScroll, which only has the purpose of keeping the screen in the same place when clicking the refresh button, and I'd prefer to keep it that way so it doesn't have any extra bells or whistles that people don't expect from it/need. That being said, I 100% don't mind turning this into a separate mod.

**Comment by UsainSrht** [comment]
👍
