### ISSUE TITLE
Make a releases page

### ISSUE THREAD

**Issue by gerro-abarabar** [Thatsmusic99/NoRefreshScroll#4]
I don't want to build it from my own 💀

**Comment by Thatsmusic99** [comment]
Does https://modrinth.com/mod/norefreshscroll count?

**Comment by gerro-abarabar** [comment]
Thanks! Next time, put it in the description other than "Well, what do you think? "

**Comment by Thatsmusic99** [comment]
No worries! I mainly expected people to find it through Modrinth rather than Github :') but seems I forgot to add it as a website anyways (probably because the repo came first), I'll change that soonish
